### ISSUE TITLE
Framework usage

### ISSUE THREAD

**Issue by mojidabckuu** [maxadamski/SwiftyRegex#2]
Hi, 
Your readme says "Of course don’t use it in apps where you have access to `NSRegularExpression`". 
So I have question: Why?
You suggest it because framework can't replace `NSRegularExpressions` or because if you have `Apple` native framework then it is better to use something native?
Thanks

**Comment by maxadamski** [comment]
Mainly because `NSRegularExpression` provides additional functionality not present in the POSIX regex standard. Otherwise I think there's nothing wrong with using POSIX regexes when you have access to the Foundation framework.
